#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar \
  position=top \
  height=32 \
  blur_radius=30 \
  color=0xff1e1e2e \
  shadow=on \
  sticky=on \
  padding_left=8 \
  padding_right=16 \
  notch_width=200 \
  display=main

##### Default Item Styles #####
sketchybar --default \
  icon.font="CaskaydiaCove NF:Bold:14.0" \
  icon.color=0xffcdd6f4 \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.font="CaskaydiaCove NF:Semibold:13.0" \
  label.color=0xffcdd6f4 \
  label.padding_left=0 \
  label.padding_right=0 \
  padding_left=8 \
  padding_right=0 \
  background.drawing=off

##### Aerospace Workspaces #####
sketchybar --add event aerospace_workspace_change

for sid in 1 2 3 4 5; do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    icon="$sid" \
    icon.highlight_color=0xff89b4fa \
    label.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_DIR/aerospace.sh $sid"
done

##### System Info - Right Side #####
sketchybar --add item clock right \
  --set clock \
  update_freq=30 \
  icon= \
  script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

##### Finalize #####
sketchybar --update
